# Generated by Django 4.2.5 on 2025-02-26 19:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True)),
                ('organization_type', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(choices=[('club', 'Club'), ('fests', 'Fests'), ('student_chapter', 'Student Chapter'), ('faculty', 'Faculty'), ('HOD', 'HOD'), ('Dean', 'Dean'), ('VC', 'VC'), ('Registrar', 'Registrar'), ('outsider', 'Outsider')], default='outsider', max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
