# Generated by Django 5.1.6 on 2025-03-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('club', 'Club'), ('fests', 'Fests'), ('student_chapter', 'Student Chapter'), ('faculty', 'Faculty'), ('HOD', 'HOD'), ('Dean', 'Dean'), ('VC', 'VC'), ('Registrar', 'Registrar'), ('outsider', 'Outsider'), ('gymkhana', 'Gymkhana')], default='outsider', max_length=20),
        ),
    ]
