# Generated by Django 5.1.6 on 2025-03-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('club', 'Club'), ('fests', 'Fests'), ('student_chapter', 'Student Chapter'), ('faculty', 'Faculty'), ('HOD', 'HOD'), ('Dean', 'Dean'), ('VC', 'VC'), ('Registrar', 'Registrar'), ('outsider', 'Outsider'), ('gymkhana', 'Gymkhana'), ('faculty_advisor', 'Faculty_advisor')], default='outsider', max_length=20),
        ),
    ]
