# Generated by Django 5.1.7 on 2025-05-11 20:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('event_details', models.TextField()),
                ('msg', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('user-cancelled', 'User-cancelled')], default='active', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('additional_comments_Venueadmin', models.CharField(default='active', max_length=1000)),
                ('reason_for_approval', models.CharField(default='active', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('location', models.TextField()),
                ('total_floors', models.IntegerField(blank=True, null=True)),
                ('photo_url', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RejectedBooking',
            fields=[
                ('rejection_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('event_details', models.TextField()),
                ('rejection_reason', models.TextField()),
                ('feedback_from_admin', models.CharField(blank=True, max_length=1000, null=True)),
                ('alternate_venues_suggestion', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rejection',
            fields=[
                ('rejection_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('msg', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback_from_admin', models.CharField(blank=True, max_length=1000, null=True)),
                ('alternate_venues_suggestion', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('venue_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo_url', models.TextField(blank=True, null=True)),
                ('capacity', models.IntegerField()),
                ('address', models.TextField()),
                ('facilities', models.JSONField(default=list)),
                ('floor_number', models.IntegerField(blank=True, null=True)),
                ('room_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
