# Generated by Django 5.2.1 on 2025-07-12 16:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('event_details', models.TextField()),
                ('msg', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('user-cancelled', 'User-cancelled')], default='active', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('additional_comments_Venueadmin', models.CharField(default='active', max_length=1000)),
                ('reason_for_approval', models.CharField(default='active', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('location', models.TextField()),
                ('total_floors', models.IntegerField(blank=True, null=True)),
                ('photo_url', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RejectedBooking',
            fields=[
                ('rejection_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('event_details', models.TextField()),
                ('rejection_reason', models.TextField()),
                ('feedback_from_admin', models.CharField(blank=True, max_length=1000, null=True)),
                ('alternate_venues_suggestion', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rejection',
            fields=[
                ('rejection_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('msg', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback_from_admin', models.CharField(blank=True, max_length=1000, null=True)),
                ('alternate_venues_suggestion', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('venue_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo_url', models.TextField(blank=True, null=True)),
                ('capacity', models.IntegerField()),
                ('address', models.TextField()),
                ('facilities', models.JSONField(default=list)),
                ('floor_number', models.TextField(blank=True, null=True)),
                ('room_number', models.CharField(blank=True, max_length=50, null=True)),
                ('class_type', models.CharField(blank=True, help_text='Class Room / Lab / Seminar Hall', max_length=100, null=True)),
                ('class_number', models.CharField(blank=True, help_text='Class Room No / Lab No / Seminar Hall No', max_length=100, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('depth_or_height', models.FloatField(blank=True, help_text='D/h', null=True)),
                ('area_sqm', models.FloatField(blank=True, null=True)),
                ('picture_urls', models.TextField(blank=True, null=True)),
                ('usage_type', models.CharField(blank=True, help_text='Hands-on session, lecture, lab, etc.', max_length=255, null=True)),
                ('venue_location', models.TextField(blank=True, null=True)),
                ('dept_incharge_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('dept_incharge_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('dept_assistant_name1', models.CharField(blank=True, max_length=255, null=True)),
                ('dept_assistant_name2', models.CharField(blank=True, max_length=255, null=True)),
                ('campus', models.CharField(blank=True, choices=[('North', 'North'), ('South', 'South')], max_length=20, null=True)),
                ('venue_admin', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
