# Generated by Django 4.2.5 on 2025-02-27 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('request_booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gymkhana', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectedBooking',
            fields=[
                ('rejection_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('event_details', models.TextField()),
                ('rejection_reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rejected_request', to='request_booking.request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejected_requests', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejected_venues', to='gymkhana.venue')),
            ],
        ),
    ]
