# Generated by Django 5.1.6 on 2025-05-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='area_sqm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='campus',
            field=models.CharField(blank=True, choices=[('North', 'North'), ('South', 'South')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='class_number',
            field=models.CharField(blank=True, help_text='Class Room No / Lab No / Seminar Hall No', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='class_type',
            field=models.CharField(blank=True, help_text='Class Room / Lab / Seminar Hall', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='dept_assistant_name1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='dept_assistant_name2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='dept_incharge_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='dept_incharge_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='depth_or_height',
            field=models.FloatField(blank=True, help_text='D/h', null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='picture_urls',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='usage_type',
            field=models.CharField(blank=True, help_text='Hands-on session, lecture, lab, etc.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='venue_location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
