# Generated by Django 5.2.1 on 2025-07-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0003_alter_booking_duration_alter_booking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejectedbooking',
            name='duration',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rejectedbooking',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
