# Generated by Django 5.2.1 on 2025-05-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0003_venue_area_sqm_venue_campus_venue_class_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='venue_admin',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
