# Generated by Django 5.1.6 on 2025-04-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0004_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='building_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='floor_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='room_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
