# Generated by Django 5.2.1 on 2025-07-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0004_alter_rejectedbooking_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='capacity',
            field=models.IntegerField(null=True),
        ),
    ]
