# Generated by Django 5.1.6 on 2025-05-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0004_venue_venue_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='floor_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
