# Generated by Django 5.2.1 on 2025-08-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0005_alter_venue_address_alter_venue_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event_details',
            field=models.TextField(default='Details not Provided', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('user-cancelled', 'User-cancelled')], default='active', max_length=100, null=True),
        ),
    ]
