# Generated by Django 5.2.1 on 2025-08-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0006_alter_booking_event_details_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
