# Generated by Django 5.1.7 on 2025-04-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0006_remove_venue_building_name_building_venue_building'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='department_incharge',
        ),
        migrations.AddField(
            model_name='building',
            name='total_floors',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
