# Generated by Django 5.2.1 on 2025-08-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0007_alter_booking_event_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('user-cancelled', 'User-cancelled')], default='active', max_length=100),
        ),
    ]
