# Generated by Django 5.1.7 on 2025-04-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0007_remove_building_department_incharge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rejectedbooking',
            name='alternate_venues_suggestion',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='rejectedbooking',
            name='feedback_from_admin',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='rejection',
            name='alternate_venues_suggestion',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='rejection',
            name='feedback_from_admin',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
