# Generated by Django 5.1.7 on 2025-04-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0008_rejectedbooking_alternate_venues_suggestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='additional_comments_Venueadmin',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], default='active', max_length=1000),
        ),
        migrations.AddField(
            model_name='booking',
            name='reason_for_approval',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], default='active', max_length=1000),
        ),
    ]
