# Generated by Django 5.1.7 on 2025-04-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0009_booking_additional_comments_venueadmin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='additional_comments_Venueadmin',
            field=models.CharField(default='active', max_length=1000),
        ),
        migrations.AlterField(
            model_name='booking',
            name='reason_for_approval',
            field=models.CharField(default='active', max_length=1000),
        ),
    ]
