# Generated by Django 5.1.7 on 2025-04-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymkhana', '0010_alter_booking_additional_comments_venueadmin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('user-cancelled', 'User-cancelled')], default='active', max_length=100),
        ),
    ]
