# Generated by Django 5.1.7 on 2025-05-11 20:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gymkhana', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CumulativeRequest',
            fields=[
                ('cumulative_request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True)),
                ('event_type', models.CharField(blank=True, max_length=255, null=True)),
                ('guest_count', models.IntegerField(default=0)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('event_details', models.TextField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('weekdays', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('num_weeks', models.IntegerField()),
                ('special_requirements', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('waiting_for_approval', 'Waiting for Approval'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('forwarded', 'Forwarded'), ('user-cancelled', 'User-Cancelled')], default='waiting_for_approval', max_length=20)),
                ('reasons', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cumulative_requests', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cumulative_venue_requests', to='gymkhana.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('event_type', models.CharField(blank=True, max_length=255, null=True)),
                ('guest_count', models.IntegerField(default=0)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('time', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('need', models.TextField(blank=True, null=True)),
                ('event_details', models.TextField()),
                ('status', models.CharField(choices=[('waiting_for_approval', 'Waiting for Approval'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('forwarded', 'Forwarded'), ('user-cancelled', 'User-Cancelled')], default='waiting_for_approval', max_length=20)),
                ('reasons', models.CharField(blank=True, max_length=255, null=True)),
                ('special_requirements', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cumulative_request_id', models.UUIDField(blank=True, null=True)),
                ('cumulative_booking', models.BooleanField(default=False)),
                ('alternate_venue_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alt_venue_1', to='gymkhana.venue')),
                ('alternate_venue_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alt_venue_2', to='gymkhana.venue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_requests', to='gymkhana.venue')),
            ],
        ),
    ]
