# Generated by Django 5.1.7 on 2025-05-11 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cumulativerequest',
            name='end_date',
        ),
    ]
