# Generated by Django 5.1.6 on 2025-03-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('waiting_for_approval', 'Waiting for Approval'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='waiting_for_approval', max_length=20),
        ),
    ]
