# Generated by Django 5.2.1 on 2025-07-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='duration',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='request',
            name='time',
            field=models.CharField(max_length=255),
        ),
    ]
