# Generated by Django 5.2.1 on 2025-07-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_booking', '0002_alter_request_duration_alter_request_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cumulativerequest',
            name='duration',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cumulativerequest',
            name='time',
            field=models.CharField(max_length=255),
        ),
    ]
