# Generated by Django 5.2.1 on 2025-05-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_booking', '0002_remove_cumulativerequest_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='additional_comments_Venueadmin',
            field=models.CharField(default='active', max_length=1000),
        ),
        migrations.AddField(
            model_name='request',
            name='alternate_venues_suggestion',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='feedback_from_admin',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='reason_for_approval',
            field=models.CharField(default='active', max_length=1000),
        ),
        migrations.AddField(
            model_name='request',
            name='rejection_reason',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
