# Generated by Django 5.1.6 on 2025-03-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_booking', '0002_alter_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('waiting_for_approval', 'Waiting for Approval'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('forwarded', 'Forwarded')], default='waiting_for_approval', max_length=20),
        ),
    ]
