# Generated by Django 5.1.7 on 2025-04-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_booking', '0003_alter_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='event_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='time',
            field=models.TimeField(),
        ),
    ]
