# Generated by Django 5.2.1 on 2025-05-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_booking', '0003_request_additional_comments_venueadmin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cumulativerequest',
            name='accept',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cumulativerequest',
            name='additional_comments',
            field=models.CharField(blank=True, default='waiting_for_approval', max_length=2000),
        ),
        migrations.AddField(
            model_name='cumulativerequest',
            name='reason_to_approve',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='cumulativerequest',
            name='reason_to_reject',
            field=models.CharField(blank=True, default='waiting_for_approval', max_length=2000),
        ),
    ]
