# Generated by Django 5.2.1 on 2025-12-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_booking', '0003_alter_cumulativerequest_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='event_details',
            field=models.TextField(null=True),
        ),
    ]
