# Generated by Django 5.2.1 on 2025-05-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_booking', '0004_cumulativerequest_accept_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cumulativerequest',
            name='suggest_alternate_venues',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='cumulativerequest',
            name='reason_to_reject',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
