# Generated by Django 5.1.7 on 2025-04-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_booking', '0004_request_additional_info_request_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='time',
            field=models.IntegerField(),
        ),
    ]
