# Generated by Django 5.2.1 on 2026-01-01 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_booking', '0004_alter_request_event_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cumulativerequest',
            name='num_weeks',
        ),
        migrations.AddField(
            model_name='cumulativerequest',
            name='end_date',
            field=models.DateField(default=datetime.date(2026, 1, 1)),
            preserve_default=False,
        ),
    ]
