# Generated by Django 5.1.7 on 2025-04-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_booking', '0005_alter_request_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='guest_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
    ]
