# Generated by Django 5.1.7 on 2025-04-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_booking', '0006_request_full_name_request_guest_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('waiting_for_approval', 'Waiting for Approval'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('forwarded', 'Forwarded'), ('user-cancelled', 'User-Cancelled')], default='waiting_for_approval', max_length=20),
        ),
    ]
