# Generated by Django 5.1.7 on 2025-04-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_booking', '0007_alter_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='special_requirements',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
